name: music_instruments
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.1.0
  connectivity_plus: ^3.0.4
  http: ^0.13.5
  screensize_utils:
    git:
      url: https://github.com/Ipilot7/ScreenSizeUtil.git
      ref: main # branch name



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/


  fonts:
    - family: Bangers
      fonts:
        - asset: assets/fonts/Bangers-Regular.ttf

    - family: GreatVibes
      fonts:
        - asset: assets/fonts/GreatVibes-Regular.ttf
        
  